import { StyleSheet } from 'react-native';
import {
  GAINSBORO,
  LIGHT_SALMON,
  MIDNIGHT_BLUE,
  PALETUR,
} from '../../../../config/color';
import { DPW } from '../../../../config/dp';
export const styles = StyleSheet.create({
  container: {
    backgroundColor: 'white',
    flex: 1,
  },
  backTextWhite: {
    width: 130 * DPW,
    fontSize: 40 * DPW,
    color: 'white',
    fontWeight: 'bold',
    marginTop: -50 * DPW,
  },
  rowFrontContainer: {
    flex: 1,
  },
  rowFront: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    marginHorizontal: 20 * DPW,
  },
  rowFront_expired: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    marginHorizontal: 20 * DPW,
  },
  card: {
    shadowOpacity: 0.5,
    elevation: 7,
    height: 180 * DPW,
    width: 550 * DPW,
    alignSelf: 'center',
    marginTop: 10 * DPW,
    marginBottom: 15 * DPW,
  },
  card_perfomed: {
    shadowOpacity: 0.5,
    elevation: 7,
    height: 180 * DPW,
    width: 550 * DPW,
    alignSelf: 'center',
    marginTop: 10 * DPW,
    marginBottom: 15 * DPW,
    backgroundColor: GAINSBORO,
  },
  card_expired: {
    shadowOpacity: 0.5,
    elevation: 7,
    height: 180 * DPW,
    width: 550 * DPW,
    alignSelf: 'center',
    marginTop: 10 * DPW,
    marginBottom: 15 * DPW,
    backgroundColor: '#FFFFE0',
  },
  rowBack: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: LIGHT_SALMON,
    height: 180 * DPW,
    width: 550 * DPW,
    borderRadius: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 30,
    marginTop: 10 * DPW,
  },
  taskCont: {
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    height: 180 * DPW,
  },
  taskCont_expired: {
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    height: 180 * DPW,
    opacity: 0.25,
  },
  taskCont_not_expired_text: {
    position: 'absolute',
    fontSize: 75 * DPW,
    left: 20 * DPW,
    fontFamily: 'BMJUA',
    top: 60 * DPW,
  },
  task1st: {
    flexDirection: 'row',
  },
  task2nd: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 10,
  },
  taskName: {
    fontFamily: 'BMJUA',
    color: MIDNIGHT_BLUE,
    fontSize: 44 * DPW,
    width: 260 * DPW,
    marginRight: 40 * DPW,
  },

  taskPrior: {
    fontFamily: 'BMJUA',
    color: MIDNIGHT_BLUE,
    fontSize: 42 * DPW,
  },
  taskExp: {
    fontFamily: 'BMJUA',
    color: 'red',
    fontSize: 30 * DPW,
    justifyContent: 'center',
    alignSelf: 'flex-start',
    top: 8 * DPW,
    marginTop: 20 * DPW,
  },
  completeBtnView: {
    marginLeft: 20 * DPW,
    marginTop: 12 * DPW,
  },
  completeTextView: {
    width: 55,
    height: 30,
    textAlign: 'center',
    fontFamily: 'BMJUA',
    borderColor: 'black',
    borderWidth: 5,
    borderRadius: 7,
    backgroundColor: 'black',
    color: 'white',
    paddingTop: 7,
  },
  backRightBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    borderRadius: 15,
  },
  backRightBtnRight: {
    backgroundColor: LIGHT_SALMON,
    height: 160 * DPW,
    right: 10 * DPW,
  },
  separator: {
    height: 15 * DPW,
    backgroundColor: PALETUR,
    width: 550 * DPW,
    borderRadius: 9,
    alignSelf: 'center',
  },
  underLine: {
    height: 20 * DPW,
    backgroundColor: PALETUR,
    width: '100%',
    alignSelf: 'center',
  },
  bottomLine: {
    height: 20 * DPW,
    backgroundColor: PALETUR,
    width: '100%',
    bottom: 0,
    position: 'absolute',
  },
  noTaskText: {
    marginTop: 200 * DPW,
    fontFamily: 'BMJUA',
    color: MIDNIGHT_BLUE,
    fontSize: 66 * DPW,
  },
  noTaskImg: {
    width: 600 * DPW,
    height: 700 * DPW,
    opacity: 0.5,
    marginTop: -100 * DPW,
  },
  addBtnContainer: {
    width: 100 * DPW,
    height: 100 * DPW,
    marginBottom: 100 * DPW,
  },
  actionBtnContainer: {
    bottom: 60 * DPW,
    left: 66 * DPW,
  },
  cardForGuide: {
    shadowOpacity: 0.5,
    height: 160 * DPW,
    width: 550 * DPW,
    alignSelf: 'center',
    marginTop: 10 * DPW,
    marginBottom: 15 * DPW,
    zIndex: 6,
    bottom: 0,
    position: 'absolute',
  },
  rowBackForGuide: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: LIGHT_SALMON,
    height: 160 * DPW,
    width: 550 * DPW,
    borderRadius: 15,
    flexDirection: 'row',
    paddingHorizontal: 30,
    position: 'absolute',
    marginTop: 10 * DPW,
    bottom: 8,
    zIndex: -1,
    opacity: 1,
  },
  deleteBtnForGuide: {
    color: 'white',
    fontSize: 20,
    marginLeft: 200 * DPW,
    marginBottom: 48 * DPW,
  },
  guideHeaderCont: {
    bottom: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  guideHeaderText: {
    textAlign: 'center',
    color: 'white',
    fontFamily: 'BMJUA',
    fontSize: 25,
  },
  guideText: {
    textAlign: 'center',
    color: 'white',
    fontFamily: 'BMJUA',
    fontSize: 18,
  },
  guideModalBtn: {
    borderColor: 'white',
    borderWidth: 6,
    padding: 20 * DPW,
    borderRadius: 20,
    width: 360 * DPW,
    alignSelf: 'center',
    marginTop: 60 * DPW,
  },
  guideModalBtnText: {
    textAlign: 'center',
    color: 'white',
    fontFamily: 'BMJUA',
    fontSize: 50 * DPW,
  },
});
