import { StyleSheet } from 'react-native';
import { DPW } from '../../config/dp';
import { MIDNIGHT_BLUE, PALETUR } from '../../config/color';
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: MIDNIGHT_BLUE,
    alignItems: 'center',
  },
  headerText: {
    paddingTop: 30 * DPW,
    alignItems: 'center',
    fontSize: 70 * DPW,
    color: 'white',
    top: 75 * DPW,
    fontFamily: 'BMJUA',
  },
  bodyContainer: {
    backgroundColor: MIDNIGHT_BLUE,
    paddingHorizontal: 20 * DPW,
    marginVertical: 30 * DPW,
    width: 550 * DPW,
    top: 100 * DPW,
  },
  idInput: {
    fontFamily: 'BMJUA',
    marginTop: 20 * DPW,
    marginBottom: 10 * DPW,
    paddingHorizontal: 10 * DPW,
    height: 120 * DPW,
    paddingLeft: 40 * DPW,
    borderRadius: 10,
    backgroundColor: 'white',
    borderWidth: 3,
    color: MIDNIGHT_BLUE,
    fontSize: 38 * DPW,
  },
  pwdInput: {
    // fontFamily:"BMJUA",
    marginTop: 20 * DPW,
    marginBottom: 10 * DPW,
    paddingHorizontal: 15 * DPW,
    height: 120 * DPW,
    borderRadius: 10,
    paddingLeft: 40 * DPW,
    backgroundColor: 'white',
    borderWidth: 3,
    color: MIDNIGHT_BLUE,
    fontWeight: 'bold',
    fontSize: 38 * DPW,
  },
  showText: {
    marginTop: 30 * DPW,
    fontSize: 25 * DPW,
    color: 'white',
  },
  loginBtnContainer: {
    backgroundColor: PALETUR,
    height: 80 * DPW,
    alignItems: 'center',
    borderRadius: 20,
    borderWidth: 3,
    borderColor: 'white',
    marginTop: 30 * DPW,
  },
  loginBtn: {
    alignItems: 'center',
    fontFamily: 'BMJUA',
    fontSize: 50 * DPW,
    color: MIDNIGHT_BLUE,
    marginTop: 12 * DPW,
  },
  kakaoLogin: {
    width: 520 * DPW,
    height: 80 * DPW,
    marginTop: 20 * DPW,
  },
  googleLogin: {
    width: 520 * DPW,
    height: 90 * DPW,
    marginRight: 10 * DPW,
  },
});
